../../bin/generate_export_file.pl       usr/lib/ace/bin
../../bin/split-cpp.pl                  usr/lib/ace/bin
../../bin/g++dep                        usr/lib/ace/bin
usr/share/ace/bin/add_rel_link.sh usr/lib/ace/bin/
usr/share/ace/bin/depgen.pl usr/lib/ace/bin/
usr/share/ace/bin/DependencyGenerator usr/lib/ace/bin/
usr/include/ace
usr/share/ace/include/makeinclude usr/lib/ace/include/
usr/include/ace/*.h
usr/include/ace/*.inl
usr/include/ace/*.cpp
usr/include/ace/os_include
usr/include/ace/Compression
usr/lib/libACE.so
usr/include/ace/ETCL/*.h
usr/include/ace/ETCL/*.inl
usr/include/ace/Monitor_Control/*.h
usr/lib/libACE_ETCL_Parser.so
usr/lib/libACE_Monitor_Control.so
usr/lib/libACE_ETCL.so
usr/lib/libACE_Compression.so
usr/lib/libACE_RLECompression.so
usr/lib/pkgconfig/ACE.pc
usr/lib/pkgconfig/ACE_ETCL.pc
usr/lib/pkgconfig/ACE_ETCL_Parser.pc
