/* ace/config.h.  Generated by configure.  */
/* ... then tweaked to look like Linux's one. */

#ifndef ACE_CONFIG_KFREEBSD_H
#define ACE_CONFIG_KFREEBSD_H
#include /**/ "ace/pre.h"

#define ACE_PLATFORM_CONFIG config-kfreebsd.h

// Slurped from config-linux-common.h
// Needed to differentiate between libc 5 and libc 6 (aka glibc).
#include <features.h>

#if (defined _XOPEN_SOURCE && (_XOPEN_SOURCE - 0) >= 500)
#  define ACE_HAS_PTHREADS_UNIX98_EXT 1
#endif /* _XOPEN_SOURCE - 0 >= 500 */

#if (defined _POSIX_C_SOURCE && (_POSIX_C_SOURCE - 0) >= 199309L)
#  if !defined (ACE_HAS_CLOCK_GETTIME)
#    define ACE_HAS_CLOCK_GETTIME 1
#    define ACE_HAS_CLOCK_SETTIME 1
#  endif  /* !ACE_HAS_CLOCK_GETTIME */
#endif  /* _POSIX_C_SOURCE >= 199309L */

#define ACE_HAS_SHM_OPEN 1
#define ACE_HAS_STRNLEN 1
#define ACE_HAS_POLL 1
#define ACE_HAS_VOIDPTR_SOCKOPT 1
#define ACE_LACKS_SYSTIME_H 1
#define ACE_HAS_SNPRINTF 1
#define ACE_HAS_SIGINFO_T 1
#define ACE_LACKS_SIGINFO_H 1
#define ACE_HAS_UCONTEXT_T 1
#define ACE_HAS_SIGTIMEDWAIT 1
#define ACE_LACKS_MSG_ACCRIGHTS 1
#define ACE_HAS_LSEEK64 1
#define ACE_HAS_P_READ_WRITE 1
#define ACE_HAS_ALT_CUSERID 1
#define ACE_HAS_STRING_CLASS 1
#define ACE_HAS_SIGWAIT 1
#define ACE_HAS_SIGSUSPEND 1
#define ACE_HAS_AIO_CALLS 1
#define ACE_HAS_XPG4_MULTIBYTE_CHAR 1
#define ACE_HAS_3_PARAM_WCSTOK 1
#define ACE_HAS_GETRUSAGE 1
#define ACE_HAS_GETRUSAGE_PROTOTYPE 1
#define ACE_HAS_CONSISTENT_SIGNAL_PROTOTYPES 1
#define ACE_HAS_HANDLE_SET_OPTIMIZED_FOR_SELECT 1
#define ACE_HAS_IP_MULTICAST 1
#define ACE_HAS_MSG 1
#define ACE_HAS_NONCONST_SELECT_TIMEVAL 1
#define ACE_HAS_GETPAGESIZE 1
#define ACE_LACKS_TIMESPEC_T 1
#define ACE_HAS_STRBUF_T 1
#define ACE_HAS_SYSV_IPC 1
#define ACE_HAS_SYS_SYSCALL_H 1
#define ACE_HAS_TIMEZONE 1
#define ACE_HAS_STRERROR 1
#define ACE_HAS_STRPTIME 1
#define ACE_HAS_SSIZE_T 1
#define ACE_HAS_SIG_ATOMIC_T 1
#define ACE_HAS_POSIX_TIME 1
#define ACE_HAS_GPERF 1
#define ACE_HAS_DIRENT 1
#define ACE_LACKS_GETIPNODEBYADDR 1
#define ACE_LACKS_GETIPNODEBYNAME 1

#define ACE_SIZEOF_WCHAR 4
#define ACE_SIZEOF_DOUBLE 8
#define ACE_SIZEOF_FLOAT 4
#define ACE_SIZEOF_INT 4
#define ACE_SIZEOF_LONG 4
#define ACE_SIZEOF_LONG_DOUBLE 12
#define ACE_SIZEOF_LONG_LONG 8
#define ACE_SIZEOF_SHORT 2
#define ACE_SIZEOF_VOID_P 4

#define ACE_HAS_SVR4_DYNAMIC_LINKING 1
#define ACE_HAS_AUTOMATIC_INIT_FINI 1

#define ACE_MT_SAFE 1
#define ACE_HAS_THREADS 1
#define ACE_HAS_PTHREADS 1
#define ACE_HAS_PTHREADS_STD 1
#define ACE_LACKS_RWLOCK_T 1
#define ACE_HAS_THREAD_SPECIFIC_STORAGE 1
#define ACE_HAS_RECURSIVE_THR_EXIT_SEMANTICS 1
#define ACE_HAS_REENTRANT_FUNCTIONS 1
#define ACE_HAS_2_PARAM_ASCTIME_R_AND_CTIME_R 1

/* Compiler requires template args when explicitly calling template
   destructor. */
#define ACE_EXPLICIT_TEMPLATE_DESTRUCTOR_TAKES_ARGS 1

/* Uses ctime_r & asctime_r with only two parameters vs. three. */


/* Platform's wcstok() takes 3 arguments */


/* Platform has BSD 4.4 sendmsg()/recvmsg() APIs. */
#define ACE_HAS_4_4BSD_SENDMSG_RECVMSG 1

/* Compiler/platform has correctly prototyped header files. */
#define ACE_HAS_CPLUSPLUS_HEADERS 1

/* Compiler supports C++ exception handling. */
#define ACE_HAS_EXCEPTIONS 1

/* Define to 1 if platform has getifaddrs(). */
#define ACE_HAS_GETIFADDRS 1

/* Denotes that GNU has cstring.h as standard which redefines memchr() */
#define ACE_HAS_GNU_CSTRING_H 1

/* Defined to 1 if platform supports ICMP over raw sockets */
#define ACE_HAS_ICMP_SUPPORT 1

/* Define to 1 if the system has the type `int16_t'. */
#define ACE_HAS_INT16_T 1

/* Define to 1 if the system has the type `int32_t'. */
#define ACE_HAS_INT32_T 1

/* Define to 1 if the system has the type `int64_t'. */
#define ACE_HAS_INT64_T 1

/* Define to 1 if the system has the type `int8_t'. */
#define ACE_HAS_INT8_T 1

/* Define to 1 if platform has memchr(). */
#define ACE_HAS_MEMCHR 1

/* Compiler supports timed mutex acquisitions (e.g.
   pthread_mutex_timedlock()). */
#define ACE_HAS_MUTEX_TIMEOUTS 1

/* Define to 1 if platform has nanosleep(). */
#define ACE_HAS_NANOSLEEP 1

/* Compiler supports new (std::nothrow) */
#define ACE_HAS_NEW_NOTHROW 1

/* Platform provides new style C++ <new> header */
#define ACE_HAS_NEW_NO_H 1

/* Platform has swab(char*, char*, ssize_t) variant. */
#define ACE_HAS_NONCONST_SWAB 1

/* Platform supports "position-independent" features provided by
   ACE_Based_Pointer<>. */
#define ACE_HAS_POSITION_INDEPENDENT_POINTERS 1

/* Platform supports POSIX getpwnam_r() function */
#define ACE_HAS_POSIX_GETPWNAM_R 1

/* Platform supports POSIX O_NONBLOCK semantics */
#define ACE_HAS_POSIX_NONBLOCK 1

/* Platform supports POSIX realtime signals */
/* #undef ACE_HAS_POSIX_REALTIME_SIGNALS */

/* Platform supports POSIX real-time semaphores (e.g., VxWorks and Solaris) */
#define ACE_HAS_POSIX_SEM 1

/* Platform supports the /proc file system and defines tid_t in <sys/procfs.h>
   */
#define ACE_HAS_PROC_FS 1

/* Define to 1 if platform has pthread_mutexattr_setkind_np(). */
#define ACE_HAS_PTHREAD_MUTEXATTR_SETKIND_NP 1

/* Define to 1 if platform has the <pthread_np.h> header file. */
/* #undef ACE_HAS_PTHREAD_NP_H */

/* pthread.h declares an enum with PTHREAD_PROCESS_PRIVATE and
   PTHREAD_PROCESS_SHARED values */
#define ACE_HAS_PTHREAD_PROCESS_ENUM 1

/* Platform's sigaction() function takes const sigaction* as 2nd parameter */
#define ACE_HAS_SIGACTION_CONSTP2 1

/* Compiler requires extern "C" functions for signals. */
#define ACE_HAS_SIG_C_FUNC 1

/* Platform supports new BSD inet_addr len field. */
#define ACE_HAS_SIN_LEN 1


/* Platform requires (struct sockaddr *) for msg_name field of struct msghdr.
   */
#define ACE_HAS_SOCKADDR_MSG_NAME 1

/* Platform provides socklen_t type, such as Linux with glibc2. */
#define ACE_HAS_SOCKLEN_T 1

/* Platform/compiler supports Standard C++ Library */
#define ACE_HAS_STANDARD_CPP_LIBRARY 1

/* */
#define ACE_HAS_STDCPP_STL_INCLUDES 1

/* Platform provides C++ <stdexcept> header */
#define ACE_HAS_STDEXCEPT_NO_H 1

/* Compiler supports standard C++ template class member specializations */
#define ACE_HAS_STD_TEMPLATE_CLASS_MEMBER_SPECIALIZATION 1

/* Compiler supports standard C++ template specializations (e.g. "template <>"
   syntax.) */
#define ACE_HAS_STD_TEMPLATE_SPECIALIZATION 1

/* Platform supports STREAMS */
#define ACE_HAS_STREAMS 1

/* Platform has <strings.h> (which contains bzero() prototype) */
#define ACE_HAS_STRINGS 1

/* Platform/compiler supports _sys_errlist symbol */
#define ACE_HAS_SYS_ERRLIST 1

/* Define to 1 if platform has the <sys/filio.h> header file. */
#define ACE_HAS_SYS_FILIO_H 1

/* Compiler/platform supports _sys_siglist array */
#define ACE_HAS_SYS_SIGLIST 1

/* Define to 1 if platform has the <sys/sockio.h> header file. */
#define ACE_HAS_SYS_SOCKIO_H 1

/* Compiler implements templates that support typedefs inside of classes used
   as formal arguments to a template class. */
#define ACE_HAS_TEMPLATE_TYPEDEFS 1

/* Platform/compiler supports timezone * as second parameter to gettimeofday()
   and has a prototype. */
#define ACE_HAS_TIMEZONE_GETTIMEOFDAY 1

/* Compiler supports the C++ typename keyword */
#define ACE_HAS_TYPENAME_KEYWORD 1

/* Define to 1 if platform has ualarm(). */
#define ACE_HAS_UALARM 1

/* Define to 1 if the system has the type `uint16_t'. */
#define ACE_HAS_UINT16_T 1

/* Define to 1 if the system has the type `uint32_t'. */
#define ACE_HAS_UINT32_T 1

/* Define to 1 if the system has the type `uint64_t'. */
#define ACE_HAS_UINT64_T 1

/* Define to 1 if the system has the type `uint8_t'. */
#define ACE_HAS_UINT8_T 1

/* Compiler supports the new using keyword for C++ namespaces. */
#define ACE_HAS_USING_KEYWORD 1

/* Define to 1 if platform has vfwprintf(). */
#define ACE_HAS_VFWPRINTF 1

/* Platform requires void * for mmap(). */
#define ACE_HAS_VOIDPTR_MMAP 1

/* Define to 1 if platform has vswprintf(). */
#define ACE_HAS_VSWPRINTF 1

/* Platform/compiler supports wchar_t */
#define ACE_HAS_WCHAR 1

/* Compiler handles explicit calling of template destructor correctly. */
#define ACE_HAS_WORKING_EXPLICIT_TEMPLATE_DESTRUCTOR 1

/* Define to signed 64 bit integer type */
#define ACE_INT64_TYPE signed long long

/* Define to the type of arg 2 for `ioctl'. */
#define ACE_IOCTL_TYPE_ARG2 int

/* iostream header does not declare ipfx (), opfx (), etc. */
#define ACE_LACKS_IOSTREAM_FX 1

/* iostreams are not supported adequately on the given platform. */
/* #undef ACE_LACKS_IOSTREAM_TOTALLY */

/* Define to 1 if platform lacks itow(). */
#define ACE_LACKS_ITOW 1

/* Platform lacks streambuf "linebuffered ()". */
#define ACE_LACKS_LINEBUFFERED_STREAMBUF 1

/* Platform lacks named POSIX semaphores (e.g., Chorus) */
#define ACE_LACKS_NAMED_POSIX_SEM 1

/* Compiler complains about use of obsolete "pragma once" */
#define ACE_LACKS_PRAGMA_ONCE 1

/* Define to 1 if the system lacks the type 'pri_t'. */
#define ACE_LACKS_PRI_T 1

/* Define to 1 if platform lacks pthread_thr_sigsetmask(). */
#define ACE_LACKS_PTHREAD_THR_SIGSETMASK 1

/* Define to 1 if platform lacks the declarations of recv_timedwait,
   send_timedwait, etc. */
#define ACE_LACKS_TIMEDWAIT_PROTOTYPES 1

/* */
#define ACE_LACKS_UNBUFFERED_STREAMBUF 1

/* Define to 1 if the system lacks the type `u_long_long'. */
#define ACE_LACKS_U_LONGLONG_T 1

/* Define to 1 if platform lacks wcsicmp(). */
#define ACE_LACKS_WCSICMP 1

/* Define to 1 if platform lacks wcsnicmp(). */
#define ACE_LACKS_WCSNICMP 1

/* Compiler's 'new' throws exception on failure (ANSI C++ behavior). */
#define ACE_NEW_THROWS_EXCEPTIONS 1

/* Flag that denotes the symbol should be exported from the DSO/DLL. */
#define ACE_Proper_Export_Flag __attribute__ ((visibility("default")))

/* Compiler's template mechanim must see source code (i.e., .cpp files). This
   is used for GNU G++. */
#define ACE_TEMPLATES_REQUIRE_SOURCE 1

/* Define to unsigned 64 bit integer type */
#define ACE_UINT64_TYPE unsigned long long

/* Platform has its standard C++ library in the namespace std. */
#define ACE_USES_STD_NAMESPACE_FOR_STDCPP_LIB 1

/* Define to 1 if you have the <dirent.h> header file, and it defines `DIR'.
   */
#define HAVE_DIRENT_H 1

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the <fstream> header file. */
#define HAVE_FSTREAM 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <iomanip> header file. */
#define HAVE_IOMANIP 1

/* Define to 1 if you have the <ios> header file. */
#define HAVE_IOS 1

/* Define to 1 if you have the <iostream> header file. */
#define HAVE_IOSTREAM 1

/* Define to 1 if you have the <istream> header file. */
#define HAVE_ISTREAM 1

/* Define to 1 if you have the `dld' library (-ldld). */
/* #undef HAVE_LIBDLD */

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <ostream> header file. */
#define HAVE_OSTREAM 1

/* */
/* #undef HAVE_RESTARTABLE_SYSCALLS */

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <streambuf> header file. */
#define HAVE_STREAMBUF 1

/* Define to 1 if you have the `strftime' function. */
#define HAVE_STRFTIME 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have <sys/wait.h> that is POSIX.1 compatible. */
#define HAVE_SYS_WAIT_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "ace-bugs@cs.wustl.edu"

/* Define to the full name of this package. */
#define PACKAGE_NAME "ACE"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "ACE 5.4.7"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "ace"

/* Define to the version of this package. */
#define PACKAGE_VERSION "5.4.7"

/* The size of a `double', as computed by sizeof. */
#define SIZEOF_DOUBLE 8

/* The size of a `float', as computed by sizeof. */
#define SIZEOF_FLOAT 4

/* The size of a `int', as computed by sizeof. */
#define SIZEOF_INT 4

/* The size of a `long', as computed by sizeof. */
#define SIZEOF_LONG 4

/* The size of a `long double', as computed by sizeof. */
#define SIZEOF_LONG_DOUBLE 12

/* The size of a `long long', as computed by sizeof. */
#define SIZEOF_LONG_LONG 8

/* The size of a `short', as computed by sizeof. */
#define SIZEOF_SHORT 2

/* The size of a `signed char', as computed by sizeof. */
#define SIZEOF_SIGNED_CHAR 1

/* The size of a `void *', as computed by sizeof. */
#define SIZEOF_VOID_P 4

/* The size of a `wchar_t', as computed by sizeof. */
#define SIZEOF_WCHAR_T 4

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

#include /**/ "ace/post.h"

#endif  /* ACE_CONFIG_KFREEBSD_H */
